*KEYWORD
$ SDM-assembled airbag master deck: control + mesh + inflator + material
$ The mesh include is generated by vektor3d and carries SET_PART 1 (control
$ volume), SET_PART 2 (all parts, for the contact below) and the flat
$ *AIRBAG_REFERENCE_GEOMETRY.
*INCLUDE
03_Control_card.k
*INCLUDE
{bag}
*INCLUDE
inflator.k
*INCLUDE
MAT.K
*CONTACT_AUTOMATIC_SINGLE_SURFACE_ID
         1
         2         0         2         0         0         0         1         1
       0.1       0.1       0.0       0.0       0.0         0       0.0       0.0
       0.0       0.0       0.0       0.0       0.0       0.0       0.0       0.0
         1       0.0         0       0.0       0.0         0         0         0
*END
